## NUMPY TUTORIALS


In [2]:
#import the module
import numpy as np

 1. np.array()

In [3]:
#convert a list into array
list1 = [3,4,59999,6,7]

# We can pass a list and specify a datatype (optional) in which we want to␣
#↪store the value in array
arr_1d = np.array(list1 , np.int32)

arr_1d

array([    3,     4, 59999,     6,     7])

In [4]:
#Data type of array
arr_1d.dtype

dtype('int32')

In [5]:
#Dimension of array
arr_1d.shape  # 1d array having 5 elements

(5,)

In [6]:
#new array (2d array)
arr_2d = np.array([[1,2,3,4],[5,6,7,8]])

In [7]:
#dimension of new array
arr_2d.shape  #rows = 2 columns = 4

(2, 4)

In [8]:
#To change shape of array
arr_2d.reshape(4,2) # we have to maintain the product of original array i.e rows into columns 8 in this case

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [9]:
#to change shape again
arr_2d.reshape(1,8)  # product of 1*8 = 8 like original array

array([[1, 2, 3, 4, 5, 6, 7, 8]])

To Visualize the Difference between 1D & 2D

• 1D will have One Opening square brackets & One closing square brackets

• 2D will have Two Opening square brackets & Two closing square brackets

In [10]:
#Convert a tuple to array
arr_from_tup = np.array((3.4,4.5,5.3,6.6))

In [12]:
#Shape of this array
arr_from_tup.shape

(4,)

In [13]:
#Data type of this array
arr_from_tup.dtype

dtype('float64')

2. np.arrange()

 We can create an array with a range of elements

In [14]:
# Create an array from 1 to 10
np.arange(start =1 , stop = 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
#Create an array from 1 to 10 with step size 3
np.arange(start = 1,stop = 10 , step = 3)

array([1, 4, 7])

In [17]:
# Right now its 1D
np.arange(1,10,2).shape


(5,)

In [18]:
# Convert to 2D
np.arange(1,10,2).reshape(5,1).shape

(5, 1)

In [19]:
np.arange(50,1,-1)

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2])

In [20]:
np.arange(1,18,3)
np.arange(1,18,3).shape
np.arange(1,18,3).reshape(2,3)


array([[ 1,  4,  7],
       [10, 13, 16]])