## NUMPY TUTORIALS


In [3]:
#import the module
import numpy as np

 1. np.array()

In [4]:
#convert a list into array
list1 = [3,4,59999,6,7]

# We can pass a list and specify a datatype (optional) in which we want to␣
#↪store the value in array
arr_1d = np.array(list1 , np.int32)

arr_1d

array([    3,     4, 59999,     6,     7])

In [6]:
#Data type of array
arr_1d.dtype

dtype('int32')

In [7]:
#Dimension of array
arr_1d.shape  # 1d array having 5 elements

(5,)

In [13]:
#new array (2d array)
arr_2d = np.array([[1,2,3,4],[5,6,7,8]])

In [16]:
#dimension of new array
arr_2d.shape  #rows = 2 columns = 4

(2, 4)

In [19]:
#To change shape of array
arr_2d.reshape(4,2) # we have to maintain the product of original array i.e rows into columns 8 in this case

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [21]:
#to change shape again
arr_2d.reshape(1,8)  # product of 1*8 = 8 like original array

array([[1, 2, 3, 4, 5, 6, 7, 8]])